In [5]:
import numpy as np
a = np.array([
             [1,2,3],
             [3,2,1]
             ])

b = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
             ])


In [ ]:
print (a.ndim) #ndim denotes the number of axis (dimensions) of the array. a and b are arrays of 1-D arrays.
print (b.ndim)
print (a.shape) #indicates the size in each dimension
print (b.shape)
print (a.size)
print (b.size)
print (a.dtype)
print (b.dtype)

2
2
(2, 3)
(3, 3)
6
9
int64
int64


In [13]:
print ( np.zeros((2, 3, 2)
                 ) )
print (np.ones_like(a))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1 1 1]
 [1 1 1]]


In [25]:
 
print ( np.arange(1, 10, 2) )
print ( np.arange(1, 11) )


[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10]
